image: Ubuntu2204

environment:
  SYMFONY_ENV: test

install:
  - sudo apt-get update
  - sudo apt-get install -y php8.1 php8.1-cli php8.1-xml php8.1-mbstring php8.1-intl php8.1-curl php8.1-zip unzip
  - php -v
  - mkdir -p ~/bin
  - curl -sS https://getcomposer.org/installer | php -- --install-dir=~/bin --filename=composer
  - source $HOME/.profile
  - composer self-update
  - composer install --no-interaction --prefer-dist

build: false

test_script:
  - php bin/phpunit

cache:
  - vendor -> composer.lock
  - ~/.composer

artifacts:
  - path: var/logs
    name: logs
