image: Ubuntu2204

environment:
  php: "8.2"
  SYMFONY_ENV: test

install:
  - sudo apt-get update
  - sudo apt-get install -y unzip
  - sudo apt upgrade -y
  - sudo add-apt-repository ppa:ondrej/php
  - sudo apt-get update
  - sudo apt-get install -y php8.2 php8.2-cli php8.2-common php8.2-curl php8.2-fpm php8.2-intl php8.2-mbstring php8.2-mysql php8.2-xml php8.2-zip
  - php -v
  - curl -sS https://getcomposer.org/installer -o composer-setup.php
  - sudo php composer-setup.php
  - rm composer-setup.php
  - composer install

build: false

test_script:
  - php bin/phpunit

cache:
  - vendor -> composer.lock
  - composer.phar
  - ~/.composer

artifacts:
  - path: var/logs
    name: logs
