image: Ubuntu2204

environment:
  php: "8.2"
  SYMFONY_ENV: test

install:
  - php -v
  - composer install

build: false

test_script:
  - php bin/phpunit

cache:
  - vendor -> composer.lock
  - ~/.composer

artifacts:
  - path: var/logs
    name: logs
